# Generated by Django 5.2.8 on 2025-11-20 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='initial_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
