# Generated by Django 4.2.1 on 2025-11-21 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_remove_business_image_business_logo_business_tagline'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='industry',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
