# Generated by Django 4.2.1 on 2025-11-23 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0005_business_address_business_city_business_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='address',
        ),
        migrations.RemoveField(
            model_name='business',
            name='city',
        ),
        migrations.RemoveField(
            model_name='business',
            name='country',
        ),
        migrations.RemoveField(
            model_name='business',
            name='email',
        ),
        migrations.RemoveField(
            model_name='business',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='business',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='business',
            name='state',
        ),
    ]
