# Generated by Django 4.2.1 on 2025-11-23 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0008_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoiceNumber',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
