# Generated by Django 6.0 on 2025-12-28 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0010_business_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
